### ISSUE TITLE
After node has been selected we don't have clicked event

### ISSUE THREAD

**Issue by mika555g** [netzerstudio/rxzu#1]
When a node is selected it's no longer triggers the selected event or clicked event, that's why need to add a click event to the base model
I can make a PR for this 

Thanks in advance

**Comment by DanielNetzer** [comment]
Hello @mika555g sorry for the late response, I'd be more than happy if you can create a PR for this.

**Comment by DanielNetzer** [comment]
@mika555g https://nforceai.github.io/rxzu/?path=/story/actions--actions
A new ClickAction has been added. You can subscribe to it.
It will trigger every time.
